/********************************************************************************
** Form generated from reading UI file 'tablecontrol.ui'
**
** Created: Wed May 18 17:27:45 2016
**      by: Qt User Interface Compiler version 4.6.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_TABLECONTROL_H
#define UI_TABLECONTROL_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>

QT_BEGIN_NAMESPACE

class Ui_TableControl
{
public:
    QLabel *lblVersion11A2;
    QLabel *lblVersion6D1;
    QLabel *lblVersion8A1;
    QLabel *lblVersion4C2;
    QLabel *lblVersion1D1;
    QLabel *lblVersion9A2;
    QLabel *lblVersion4B2;
    QLabel *lblVersion6C2;
    QLabel *lblVersion5C2;
    QLabel *lblVersion11B1;
    QLabel *lblVersion1B2;
    QLabel *lblVersion11B2;
    QLabel *lblVersion10D2;
    QLabel *lblVersion2A1;
    QLabel *lblVersion10B1;
    QLabel *lblTitle2;
    QLabel *lblVersion4A1;
    QLabel *lblVersion5B2;
    QLabel *lblVersion10C1;
    QLabel *lblVersion3A2;
    QLabel *lblVersion6A1;
    QLabel *lblVersion8B2;
    QLabel *lblVersion10A2;
    QLabel *lblVersion8D2;
    QLabel *lblVersion1D2;
    QLabel *lblVersion10D1;
    QLabel *lblVersion3D2;
    QLabel *lblVersion11D2;
    QLabel *lblVersion7B1;
    QLabel *lblVersion9B1;
    QLabel *lblVersion4D1;
    QLabel *lblVersion6A2;
    QLabel *lblVersion6B1;
    QLabel *lblVersion6B2;
    QLabel *lblVersion11C1;
    QLabel *lblVersion9D2;
    QLabel *lblVersion4D2;
    QLabel *lblVersion8B1;
    QLabel *lblVersion7A1;
    QLabel *lblVersion2B2;
    QLabel *lblVersion2C1;
    QLabel *lblDeviceName7;
    QLabel *lblVersion9B2;
    QLabel *lblTitle1;
    QLabel *lblVersion4A2;
    QLabel *lblVersion4B1;
    QLabel *lblVersion10A1;
    QLabel *lblVersion1C1;
    QLabel *lblVersion3D1;
    QLabel *lblVersion5A2;
    QLabel *lblVersion9A1;
    QLabel *lblVersion7C1;
    QLabel *lblVersion4C1;
    QLabel *lblVersion5D1;
    QLabel *lblVersion8C1;
    QLabel *lblVersion11A1;
    QLabel *lblDeviceName9;
    QLabel *lblVersion7D2;
    QLabel *lblVersion5A1;
    QLabel *lblVersion10C2;
    QLabel *lblDeviceName5;
    QLabel *lblDeviceName2;
    QLabel *lblVersion9C1;
    QLabel *lblVersion7D1;
    QLabel *lblVersion2B1;
    QLabel *lblVersion9C2;
    QLabel *lblVersion3C2;
    QLabel *lblDeviceName10;
    QLabel *lblVersion3B1;
    QLabel *lblVersion7C2;
    QLabel *lblDeviceName8;
    QLabel *lblVersion8A2;
    QLabel *lblVersion5C1;
    QLabel *lblVersion11D1;
    QLabel *lblVersion6C1;
    QLabel *lblVersion2D2;
    QLabel *lblVersion8D1;
    QLabel *lblVersion7A2;
    QLabel *lblVersion1C2;
    QLabel *lblVersion1A2;
    QLabel *lblDeviceName6;
    QLabel *lblVersion1B1;
    QLabel *lblVersion7B2;
    QLabel *lblVersion3B2;
    QLabel *lblDeviceName1;
    QLabel *lblVersion3A1;
    QLabel *lblDeviceName3;
    QLabel *lblVersion2A2;
    QLabel *lblDeviceName4;
    QLabel *lblVersion2C2;
    QLabel *lblVersion6D2;
    QLabel *lblVersion9D1;
    QLabel *lblVersion8C2;
    QLabel *lblVersion3C1;
    QLabel *lblVersion1A1;
    QLabel *lblVersion10B2;
    QLabel *lblVersion5B1;
    QLabel *lblVersion11C2;
    QLabel *lblDeviceName11;
    QLabel *lblVersion2D1;
    QLabel *lblVersion5D2;

    void setupUi(QDialog *TableControl)
    {
        if (TableControl->objectName().isEmpty())
            TableControl->setObjectName(QString::fromUtf8("TableControl"));
        TableControl->resize(895, 475);
        TableControl->setStyleSheet(QString::fromUtf8("QLabel\n"
"{\n"
"	color: white;\n"
"	border: 2px groove, gray;\n"
"    border-color: gray;\n"
"	font: 18px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"	background-color: black;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"	font: 18px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"    color: black;\n"
"	background-color: rgb(133, 133, 198);\n"
"	border:1px solid white;\n"
"	border-radius: 5px;\n"
"}"));
        lblVersion11A2 = new QLabel(TableControl);
        lblVersion11A2->setObjectName(QString::fromUtf8("lblVersion11A2"));
        lblVersion11A2->setGeometry(QRect(797, 428, 91, 40));
        lblVersion11A2->setAlignment(Qt::AlignCenter);
        lblVersion6D1 = new QLabel(TableControl);
        lblVersion6D1->setObjectName(QString::fromUtf8("lblVersion6D1"));
        lblVersion6D1->setGeometry(QRect(441, 238, 91, 40));
        lblVersion6D1->setAlignment(Qt::AlignCenter);
        lblVersion8A1 = new QLabel(TableControl);
        lblVersion8A1->setObjectName(QString::fromUtf8("lblVersion8A1"));
        lblVersion8A1->setGeometry(QRect(174, 314, 91, 40));
        lblVersion8A1->setAlignment(Qt::AlignCenter);
        lblVersion4C2 = new QLabel(TableControl);
        lblVersion4C2->setObjectName(QString::fromUtf8("lblVersion4C2"));
        lblVersion4C2->setGeometry(QRect(619, 162, 91, 40));
        lblVersion4C2->setAlignment(Qt::AlignCenter);
        lblVersion1D1 = new QLabel(TableControl);
        lblVersion1D1->setObjectName(QString::fromUtf8("lblVersion1D1"));
        lblVersion1D1->setGeometry(QRect(441, 48, 91, 40));
        lblVersion1D1->setAlignment(Qt::AlignCenter);
        lblVersion9A2 = new QLabel(TableControl);
        lblVersion9A2->setObjectName(QString::fromUtf8("lblVersion9A2"));
        lblVersion9A2->setGeometry(QRect(797, 352, 91, 40));
        lblVersion9A2->setAlignment(Qt::AlignCenter);
        lblVersion4B2 = new QLabel(TableControl);
        lblVersion4B2->setObjectName(QString::fromUtf8("lblVersion4B2"));
        lblVersion4B2->setGeometry(QRect(708, 162, 91, 40));
        lblVersion4B2->setAlignment(Qt::AlignCenter);
        lblVersion6C2 = new QLabel(TableControl);
        lblVersion6C2->setObjectName(QString::fromUtf8("lblVersion6C2"));
        lblVersion6C2->setGeometry(QRect(619, 238, 91, 40));
        lblVersion6C2->setAlignment(Qt::AlignCenter);
        lblVersion5C2 = new QLabel(TableControl);
        lblVersion5C2->setObjectName(QString::fromUtf8("lblVersion5C2"));
        lblVersion5C2->setGeometry(QRect(619, 200, 91, 40));
        lblVersion5C2->setAlignment(Qt::AlignCenter);
        lblVersion11B1 = new QLabel(TableControl);
        lblVersion11B1->setObjectName(QString::fromUtf8("lblVersion11B1"));
        lblVersion11B1->setGeometry(QRect(263, 428, 91, 40));
        lblVersion11B1->setAlignment(Qt::AlignCenter);
        lblVersion1B2 = new QLabel(TableControl);
        lblVersion1B2->setObjectName(QString::fromUtf8("lblVersion1B2"));
        lblVersion1B2->setGeometry(QRect(708, 48, 91, 40));
        lblVersion1B2->setAlignment(Qt::AlignCenter);
        lblVersion11B2 = new QLabel(TableControl);
        lblVersion11B2->setObjectName(QString::fromUtf8("lblVersion11B2"));
        lblVersion11B2->setGeometry(QRect(708, 428, 91, 40));
        lblVersion11B2->setAlignment(Qt::AlignCenter);
        lblVersion10D2 = new QLabel(TableControl);
        lblVersion10D2->setObjectName(QString::fromUtf8("lblVersion10D2"));
        lblVersion10D2->setGeometry(QRect(530, 390, 91, 40));
        lblVersion10D2->setAlignment(Qt::AlignCenter);
        lblVersion2A1 = new QLabel(TableControl);
        lblVersion2A1->setObjectName(QString::fromUtf8("lblVersion2A1"));
        lblVersion2A1->setGeometry(QRect(174, 86, 91, 40));
        lblVersion2A1->setAlignment(Qt::AlignCenter);
        lblVersion10B1 = new QLabel(TableControl);
        lblVersion10B1->setObjectName(QString::fromUtf8("lblVersion10B1"));
        lblVersion10B1->setGeometry(QRect(263, 390, 91, 40));
        lblVersion10B1->setAlignment(Qt::AlignCenter);
        lblTitle2 = new QLabel(TableControl);
        lblTitle2->setObjectName(QString::fromUtf8("lblTitle2"));
        lblTitle2->setGeometry(QRect(174, 10, 714, 40));
        lblTitle2->setAlignment(Qt::AlignCenter);
        lblVersion4A1 = new QLabel(TableControl);
        lblVersion4A1->setObjectName(QString::fromUtf8("lblVersion4A1"));
        lblVersion4A1->setGeometry(QRect(174, 162, 91, 40));
        lblVersion4A1->setAlignment(Qt::AlignCenter);
        lblVersion5B2 = new QLabel(TableControl);
        lblVersion5B2->setObjectName(QString::fromUtf8("lblVersion5B2"));
        lblVersion5B2->setGeometry(QRect(708, 200, 91, 40));
        lblVersion5B2->setAlignment(Qt::AlignCenter);
        lblVersion10C1 = new QLabel(TableControl);
        lblVersion10C1->setObjectName(QString::fromUtf8("lblVersion10C1"));
        lblVersion10C1->setGeometry(QRect(352, 390, 91, 40));
        lblVersion10C1->setAlignment(Qt::AlignCenter);
        lblVersion3A2 = new QLabel(TableControl);
        lblVersion3A2->setObjectName(QString::fromUtf8("lblVersion3A2"));
        lblVersion3A2->setGeometry(QRect(797, 124, 91, 40));
        lblVersion3A2->setAlignment(Qt::AlignCenter);
        lblVersion6A1 = new QLabel(TableControl);
        lblVersion6A1->setObjectName(QString::fromUtf8("lblVersion6A1"));
        lblVersion6A1->setGeometry(QRect(174, 238, 91, 40));
        lblVersion6A1->setAlignment(Qt::AlignCenter);
        lblVersion8B2 = new QLabel(TableControl);
        lblVersion8B2->setObjectName(QString::fromUtf8("lblVersion8B2"));
        lblVersion8B2->setGeometry(QRect(708, 314, 91, 40));
        lblVersion8B2->setAlignment(Qt::AlignCenter);
        lblVersion10A2 = new QLabel(TableControl);
        lblVersion10A2->setObjectName(QString::fromUtf8("lblVersion10A2"));
        lblVersion10A2->setGeometry(QRect(797, 390, 91, 40));
        lblVersion10A2->setAlignment(Qt::AlignCenter);
        lblVersion8D2 = new QLabel(TableControl);
        lblVersion8D2->setObjectName(QString::fromUtf8("lblVersion8D2"));
        lblVersion8D2->setGeometry(QRect(530, 314, 91, 40));
        lblVersion8D2->setAlignment(Qt::AlignCenter);
        lblVersion1D2 = new QLabel(TableControl);
        lblVersion1D2->setObjectName(QString::fromUtf8("lblVersion1D2"));
        lblVersion1D2->setGeometry(QRect(530, 48, 91, 40));
        lblVersion1D2->setAlignment(Qt::AlignCenter);
        lblVersion10D1 = new QLabel(TableControl);
        lblVersion10D1->setObjectName(QString::fromUtf8("lblVersion10D1"));
        lblVersion10D1->setGeometry(QRect(441, 390, 91, 40));
        lblVersion10D1->setAlignment(Qt::AlignCenter);
        lblVersion3D2 = new QLabel(TableControl);
        lblVersion3D2->setObjectName(QString::fromUtf8("lblVersion3D2"));
        lblVersion3D2->setGeometry(QRect(530, 124, 91, 40));
        lblVersion3D2->setAlignment(Qt::AlignCenter);
        lblVersion11D2 = new QLabel(TableControl);
        lblVersion11D2->setObjectName(QString::fromUtf8("lblVersion11D2"));
        lblVersion11D2->setGeometry(QRect(530, 428, 91, 40));
        lblVersion11D2->setAlignment(Qt::AlignCenter);
        lblVersion7B1 = new QLabel(TableControl);
        lblVersion7B1->setObjectName(QString::fromUtf8("lblVersion7B1"));
        lblVersion7B1->setGeometry(QRect(263, 276, 91, 40));
        lblVersion7B1->setAlignment(Qt::AlignCenter);
        lblVersion9B1 = new QLabel(TableControl);
        lblVersion9B1->setObjectName(QString::fromUtf8("lblVersion9B1"));
        lblVersion9B1->setGeometry(QRect(263, 352, 91, 40));
        lblVersion9B1->setAlignment(Qt::AlignCenter);
        lblVersion4D1 = new QLabel(TableControl);
        lblVersion4D1->setObjectName(QString::fromUtf8("lblVersion4D1"));
        lblVersion4D1->setGeometry(QRect(441, 162, 91, 40));
        lblVersion4D1->setAlignment(Qt::AlignCenter);
        lblVersion6A2 = new QLabel(TableControl);
        lblVersion6A2->setObjectName(QString::fromUtf8("lblVersion6A2"));
        lblVersion6A2->setGeometry(QRect(797, 238, 91, 40));
        lblVersion6A2->setAlignment(Qt::AlignCenter);
        lblVersion6B1 = new QLabel(TableControl);
        lblVersion6B1->setObjectName(QString::fromUtf8("lblVersion6B1"));
        lblVersion6B1->setGeometry(QRect(263, 238, 91, 40));
        lblVersion6B1->setAlignment(Qt::AlignCenter);
        lblVersion6B2 = new QLabel(TableControl);
        lblVersion6B2->setObjectName(QString::fromUtf8("lblVersion6B2"));
        lblVersion6B2->setGeometry(QRect(708, 238, 91, 40));
        lblVersion6B2->setAlignment(Qt::AlignCenter);
        lblVersion11C1 = new QLabel(TableControl);
        lblVersion11C1->setObjectName(QString::fromUtf8("lblVersion11C1"));
        lblVersion11C1->setGeometry(QRect(352, 428, 91, 40));
        lblVersion11C1->setAlignment(Qt::AlignCenter);
        lblVersion9D2 = new QLabel(TableControl);
        lblVersion9D2->setObjectName(QString::fromUtf8("lblVersion9D2"));
        lblVersion9D2->setGeometry(QRect(530, 352, 91, 40));
        lblVersion9D2->setAlignment(Qt::AlignCenter);
        lblVersion4D2 = new QLabel(TableControl);
        lblVersion4D2->setObjectName(QString::fromUtf8("lblVersion4D2"));
        lblVersion4D2->setGeometry(QRect(530, 162, 91, 40));
        lblVersion4D2->setAlignment(Qt::AlignCenter);
        lblVersion8B1 = new QLabel(TableControl);
        lblVersion8B1->setObjectName(QString::fromUtf8("lblVersion8B1"));
        lblVersion8B1->setGeometry(QRect(263, 314, 91, 40));
        lblVersion8B1->setAlignment(Qt::AlignCenter);
        lblVersion7A1 = new QLabel(TableControl);
        lblVersion7A1->setObjectName(QString::fromUtf8("lblVersion7A1"));
        lblVersion7A1->setGeometry(QRect(174, 276, 91, 40));
        lblVersion7A1->setAlignment(Qt::AlignCenter);
        lblVersion2B2 = new QLabel(TableControl);
        lblVersion2B2->setObjectName(QString::fromUtf8("lblVersion2B2"));
        lblVersion2B2->setGeometry(QRect(708, 86, 91, 40));
        lblVersion2B2->setAlignment(Qt::AlignCenter);
        lblVersion2C1 = new QLabel(TableControl);
        lblVersion2C1->setObjectName(QString::fromUtf8("lblVersion2C1"));
        lblVersion2C1->setGeometry(QRect(352, 86, 91, 40));
        lblVersion2C1->setAlignment(Qt::AlignCenter);
        lblDeviceName7 = new QLabel(TableControl);
        lblDeviceName7->setObjectName(QString::fromUtf8("lblDeviceName7"));
        lblDeviceName7->setGeometry(QRect(5, 276, 171, 40));
        lblDeviceName7->setAlignment(Qt::AlignCenter);
        lblVersion9B2 = new QLabel(TableControl);
        lblVersion9B2->setObjectName(QString::fromUtf8("lblVersion9B2"));
        lblVersion9B2->setGeometry(QRect(708, 352, 91, 40));
        lblVersion9B2->setAlignment(Qt::AlignCenter);
        lblTitle1 = new QLabel(TableControl);
        lblTitle1->setObjectName(QString::fromUtf8("lblTitle1"));
        lblTitle1->setGeometry(QRect(5, 10, 171, 40));
        lblTitle1->setAlignment(Qt::AlignCenter);
        lblVersion4A2 = new QLabel(TableControl);
        lblVersion4A2->setObjectName(QString::fromUtf8("lblVersion4A2"));
        lblVersion4A2->setGeometry(QRect(797, 162, 91, 40));
        lblVersion4A2->setAlignment(Qt::AlignCenter);
        lblVersion4B1 = new QLabel(TableControl);
        lblVersion4B1->setObjectName(QString::fromUtf8("lblVersion4B1"));
        lblVersion4B1->setGeometry(QRect(263, 162, 91, 40));
        lblVersion4B1->setAlignment(Qt::AlignCenter);
        lblVersion10A1 = new QLabel(TableControl);
        lblVersion10A1->setObjectName(QString::fromUtf8("lblVersion10A1"));
        lblVersion10A1->setGeometry(QRect(174, 390, 91, 40));
        lblVersion10A1->setAlignment(Qt::AlignCenter);
        lblVersion1C1 = new QLabel(TableControl);
        lblVersion1C1->setObjectName(QString::fromUtf8("lblVersion1C1"));
        lblVersion1C1->setGeometry(QRect(352, 48, 91, 40));
        lblVersion1C1->setAlignment(Qt::AlignCenter);
        lblVersion3D1 = new QLabel(TableControl);
        lblVersion3D1->setObjectName(QString::fromUtf8("lblVersion3D1"));
        lblVersion3D1->setGeometry(QRect(441, 124, 91, 40));
        lblVersion3D1->setAlignment(Qt::AlignCenter);
        lblVersion5A2 = new QLabel(TableControl);
        lblVersion5A2->setObjectName(QString::fromUtf8("lblVersion5A2"));
        lblVersion5A2->setGeometry(QRect(797, 200, 91, 40));
        lblVersion5A2->setAlignment(Qt::AlignCenter);
        lblVersion9A1 = new QLabel(TableControl);
        lblVersion9A1->setObjectName(QString::fromUtf8("lblVersion9A1"));
        lblVersion9A1->setGeometry(QRect(174, 352, 91, 40));
        lblVersion9A1->setAlignment(Qt::AlignCenter);
        lblVersion7C1 = new QLabel(TableControl);
        lblVersion7C1->setObjectName(QString::fromUtf8("lblVersion7C1"));
        lblVersion7C1->setGeometry(QRect(352, 276, 91, 40));
        lblVersion7C1->setAlignment(Qt::AlignCenter);
        lblVersion4C1 = new QLabel(TableControl);
        lblVersion4C1->setObjectName(QString::fromUtf8("lblVersion4C1"));
        lblVersion4C1->setGeometry(QRect(352, 162, 91, 40));
        lblVersion4C1->setAlignment(Qt::AlignCenter);
        lblVersion5D1 = new QLabel(TableControl);
        lblVersion5D1->setObjectName(QString::fromUtf8("lblVersion5D1"));
        lblVersion5D1->setGeometry(QRect(441, 200, 91, 40));
        lblVersion5D1->setAlignment(Qt::AlignCenter);
        lblVersion8C1 = new QLabel(TableControl);
        lblVersion8C1->setObjectName(QString::fromUtf8("lblVersion8C1"));
        lblVersion8C1->setGeometry(QRect(352, 314, 91, 40));
        lblVersion8C1->setAlignment(Qt::AlignCenter);
        lblVersion11A1 = new QLabel(TableControl);
        lblVersion11A1->setObjectName(QString::fromUtf8("lblVersion11A1"));
        lblVersion11A1->setGeometry(QRect(174, 428, 91, 40));
        lblVersion11A1->setAlignment(Qt::AlignCenter);
        lblDeviceName9 = new QLabel(TableControl);
        lblDeviceName9->setObjectName(QString::fromUtf8("lblDeviceName9"));
        lblDeviceName9->setGeometry(QRect(5, 352, 171, 40));
        lblDeviceName9->setAlignment(Qt::AlignCenter);
        lblVersion7D2 = new QLabel(TableControl);
        lblVersion7D2->setObjectName(QString::fromUtf8("lblVersion7D2"));
        lblVersion7D2->setGeometry(QRect(530, 276, 91, 40));
        lblVersion7D2->setAlignment(Qt::AlignCenter);
        lblVersion5A1 = new QLabel(TableControl);
        lblVersion5A1->setObjectName(QString::fromUtf8("lblVersion5A1"));
        lblVersion5A1->setGeometry(QRect(174, 200, 91, 40));
        lblVersion5A1->setAlignment(Qt::AlignCenter);
        lblVersion10C2 = new QLabel(TableControl);
        lblVersion10C2->setObjectName(QString::fromUtf8("lblVersion10C2"));
        lblVersion10C2->setGeometry(QRect(619, 390, 91, 40));
        lblVersion10C2->setAlignment(Qt::AlignCenter);
        lblDeviceName5 = new QLabel(TableControl);
        lblDeviceName5->setObjectName(QString::fromUtf8("lblDeviceName5"));
        lblDeviceName5->setGeometry(QRect(5, 200, 171, 40));
        lblDeviceName5->setAlignment(Qt::AlignCenter);
        lblDeviceName2 = new QLabel(TableControl);
        lblDeviceName2->setObjectName(QString::fromUtf8("lblDeviceName2"));
        lblDeviceName2->setGeometry(QRect(5, 86, 171, 40));
        lblDeviceName2->setAlignment(Qt::AlignCenter);
        lblVersion9C1 = new QLabel(TableControl);
        lblVersion9C1->setObjectName(QString::fromUtf8("lblVersion9C1"));
        lblVersion9C1->setGeometry(QRect(352, 352, 91, 40));
        lblVersion9C1->setAlignment(Qt::AlignCenter);
        lblVersion7D1 = new QLabel(TableControl);
        lblVersion7D1->setObjectName(QString::fromUtf8("lblVersion7D1"));
        lblVersion7D1->setGeometry(QRect(441, 276, 91, 40));
        lblVersion7D1->setAlignment(Qt::AlignCenter);
        lblVersion2B1 = new QLabel(TableControl);
        lblVersion2B1->setObjectName(QString::fromUtf8("lblVersion2B1"));
        lblVersion2B1->setGeometry(QRect(263, 86, 91, 40));
        lblVersion2B1->setAlignment(Qt::AlignCenter);
        lblVersion9C2 = new QLabel(TableControl);
        lblVersion9C2->setObjectName(QString::fromUtf8("lblVersion9C2"));
        lblVersion9C2->setGeometry(QRect(619, 352, 91, 40));
        lblVersion9C2->setAlignment(Qt::AlignCenter);
        lblVersion3C2 = new QLabel(TableControl);
        lblVersion3C2->setObjectName(QString::fromUtf8("lblVersion3C2"));
        lblVersion3C2->setGeometry(QRect(619, 124, 91, 40));
        lblVersion3C2->setAlignment(Qt::AlignCenter);
        lblDeviceName10 = new QLabel(TableControl);
        lblDeviceName10->setObjectName(QString::fromUtf8("lblDeviceName10"));
        lblDeviceName10->setGeometry(QRect(5, 390, 171, 40));
        lblDeviceName10->setAlignment(Qt::AlignCenter);
        lblVersion3B1 = new QLabel(TableControl);
        lblVersion3B1->setObjectName(QString::fromUtf8("lblVersion3B1"));
        lblVersion3B1->setGeometry(QRect(263, 124, 91, 40));
        lblVersion3B1->setAlignment(Qt::AlignCenter);
        lblVersion7C2 = new QLabel(TableControl);
        lblVersion7C2->setObjectName(QString::fromUtf8("lblVersion7C2"));
        lblVersion7C2->setGeometry(QRect(619, 276, 91, 40));
        lblVersion7C2->setAlignment(Qt::AlignCenter);
        lblDeviceName8 = new QLabel(TableControl);
        lblDeviceName8->setObjectName(QString::fromUtf8("lblDeviceName8"));
        lblDeviceName8->setGeometry(QRect(5, 314, 171, 40));
        lblDeviceName8->setAlignment(Qt::AlignCenter);
        lblVersion8A2 = new QLabel(TableControl);
        lblVersion8A2->setObjectName(QString::fromUtf8("lblVersion8A2"));
        lblVersion8A2->setGeometry(QRect(797, 314, 91, 40));
        lblVersion8A2->setAlignment(Qt::AlignCenter);
        lblVersion5C1 = new QLabel(TableControl);
        lblVersion5C1->setObjectName(QString::fromUtf8("lblVersion5C1"));
        lblVersion5C1->setGeometry(QRect(352, 200, 91, 40));
        lblVersion5C1->setAlignment(Qt::AlignCenter);
        lblVersion11D1 = new QLabel(TableControl);
        lblVersion11D1->setObjectName(QString::fromUtf8("lblVersion11D1"));
        lblVersion11D1->setGeometry(QRect(441, 428, 91, 40));
        lblVersion11D1->setAlignment(Qt::AlignCenter);
        lblVersion6C1 = new QLabel(TableControl);
        lblVersion6C1->setObjectName(QString::fromUtf8("lblVersion6C1"));
        lblVersion6C1->setGeometry(QRect(352, 238, 91, 40));
        lblVersion6C1->setAlignment(Qt::AlignCenter);
        lblVersion2D2 = new QLabel(TableControl);
        lblVersion2D2->setObjectName(QString::fromUtf8("lblVersion2D2"));
        lblVersion2D2->setGeometry(QRect(530, 86, 91, 40));
        lblVersion2D2->setAlignment(Qt::AlignCenter);
        lblVersion8D1 = new QLabel(TableControl);
        lblVersion8D1->setObjectName(QString::fromUtf8("lblVersion8D1"));
        lblVersion8D1->setGeometry(QRect(441, 314, 91, 40));
        lblVersion8D1->setAlignment(Qt::AlignCenter);
        lblVersion7A2 = new QLabel(TableControl);
        lblVersion7A2->setObjectName(QString::fromUtf8("lblVersion7A2"));
        lblVersion7A2->setGeometry(QRect(797, 276, 91, 40));
        lblVersion7A2->setAlignment(Qt::AlignCenter);
        lblVersion1C2 = new QLabel(TableControl);
        lblVersion1C2->setObjectName(QString::fromUtf8("lblVersion1C2"));
        lblVersion1C2->setGeometry(QRect(619, 48, 91, 40));
        lblVersion1C2->setAlignment(Qt::AlignCenter);
        lblVersion1A2 = new QLabel(TableControl);
        lblVersion1A2->setObjectName(QString::fromUtf8("lblVersion1A2"));
        lblVersion1A2->setGeometry(QRect(797, 48, 91, 40));
        lblVersion1A2->setAlignment(Qt::AlignCenter);
        lblDeviceName6 = new QLabel(TableControl);
        lblDeviceName6->setObjectName(QString::fromUtf8("lblDeviceName6"));
        lblDeviceName6->setGeometry(QRect(5, 238, 171, 40));
        lblDeviceName6->setAlignment(Qt::AlignCenter);
        lblVersion1B1 = new QLabel(TableControl);
        lblVersion1B1->setObjectName(QString::fromUtf8("lblVersion1B1"));
        lblVersion1B1->setGeometry(QRect(263, 48, 91, 40));
        lblVersion1B1->setAlignment(Qt::AlignCenter);
        lblVersion7B2 = new QLabel(TableControl);
        lblVersion7B2->setObjectName(QString::fromUtf8("lblVersion7B2"));
        lblVersion7B2->setGeometry(QRect(708, 276, 91, 40));
        lblVersion7B2->setAlignment(Qt::AlignCenter);
        lblVersion3B2 = new QLabel(TableControl);
        lblVersion3B2->setObjectName(QString::fromUtf8("lblVersion3B2"));
        lblVersion3B2->setGeometry(QRect(708, 124, 91, 40));
        lblVersion3B2->setAlignment(Qt::AlignCenter);
        lblDeviceName1 = new QLabel(TableControl);
        lblDeviceName1->setObjectName(QString::fromUtf8("lblDeviceName1"));
        lblDeviceName1->setGeometry(QRect(5, 48, 171, 40));
        lblDeviceName1->setAlignment(Qt::AlignCenter);
        lblVersion3A1 = new QLabel(TableControl);
        lblVersion3A1->setObjectName(QString::fromUtf8("lblVersion3A1"));
        lblVersion3A1->setGeometry(QRect(174, 124, 91, 40));
        lblVersion3A1->setAlignment(Qt::AlignCenter);
        lblDeviceName3 = new QLabel(TableControl);
        lblDeviceName3->setObjectName(QString::fromUtf8("lblDeviceName3"));
        lblDeviceName3->setGeometry(QRect(5, 124, 171, 40));
        lblDeviceName3->setAlignment(Qt::AlignCenter);
        lblVersion2A2 = new QLabel(TableControl);
        lblVersion2A2->setObjectName(QString::fromUtf8("lblVersion2A2"));
        lblVersion2A2->setGeometry(QRect(797, 86, 91, 40));
        lblVersion2A2->setAlignment(Qt::AlignCenter);
        lblDeviceName4 = new QLabel(TableControl);
        lblDeviceName4->setObjectName(QString::fromUtf8("lblDeviceName4"));
        lblDeviceName4->setGeometry(QRect(5, 162, 171, 40));
        lblDeviceName4->setAlignment(Qt::AlignCenter);
        lblVersion2C2 = new QLabel(TableControl);
        lblVersion2C2->setObjectName(QString::fromUtf8("lblVersion2C2"));
        lblVersion2C2->setGeometry(QRect(619, 86, 91, 40));
        lblVersion2C2->setAlignment(Qt::AlignCenter);
        lblVersion6D2 = new QLabel(TableControl);
        lblVersion6D2->setObjectName(QString::fromUtf8("lblVersion6D2"));
        lblVersion6D2->setGeometry(QRect(530, 238, 91, 40));
        lblVersion6D2->setAlignment(Qt::AlignCenter);
        lblVersion9D1 = new QLabel(TableControl);
        lblVersion9D1->setObjectName(QString::fromUtf8("lblVersion9D1"));
        lblVersion9D1->setGeometry(QRect(441, 352, 91, 40));
        lblVersion9D1->setAlignment(Qt::AlignCenter);
        lblVersion8C2 = new QLabel(TableControl);
        lblVersion8C2->setObjectName(QString::fromUtf8("lblVersion8C2"));
        lblVersion8C2->setGeometry(QRect(619, 314, 91, 40));
        lblVersion8C2->setAlignment(Qt::AlignCenter);
        lblVersion3C1 = new QLabel(TableControl);
        lblVersion3C1->setObjectName(QString::fromUtf8("lblVersion3C1"));
        lblVersion3C1->setGeometry(QRect(352, 124, 91, 40));
        lblVersion3C1->setAlignment(Qt::AlignCenter);
        lblVersion1A1 = new QLabel(TableControl);
        lblVersion1A1->setObjectName(QString::fromUtf8("lblVersion1A1"));
        lblVersion1A1->setGeometry(QRect(174, 48, 91, 40));
        lblVersion1A1->setAlignment(Qt::AlignCenter);
        lblVersion10B2 = new QLabel(TableControl);
        lblVersion10B2->setObjectName(QString::fromUtf8("lblVersion10B2"));
        lblVersion10B2->setGeometry(QRect(708, 390, 91, 40));
        lblVersion10B2->setAlignment(Qt::AlignCenter);
        lblVersion5B1 = new QLabel(TableControl);
        lblVersion5B1->setObjectName(QString::fromUtf8("lblVersion5B1"));
        lblVersion5B1->setGeometry(QRect(263, 200, 91, 40));
        lblVersion5B1->setAlignment(Qt::AlignCenter);
        lblVersion11C2 = new QLabel(TableControl);
        lblVersion11C2->setObjectName(QString::fromUtf8("lblVersion11C2"));
        lblVersion11C2->setGeometry(QRect(619, 428, 91, 40));
        lblVersion11C2->setAlignment(Qt::AlignCenter);
        lblDeviceName11 = new QLabel(TableControl);
        lblDeviceName11->setObjectName(QString::fromUtf8("lblDeviceName11"));
        lblDeviceName11->setGeometry(QRect(5, 428, 171, 40));
        lblDeviceName11->setAlignment(Qt::AlignCenter);
        lblVersion2D1 = new QLabel(TableControl);
        lblVersion2D1->setObjectName(QString::fromUtf8("lblVersion2D1"));
        lblVersion2D1->setGeometry(QRect(441, 86, 91, 40));
        lblVersion2D1->setAlignment(Qt::AlignCenter);
        lblVersion5D2 = new QLabel(TableControl);
        lblVersion5D2->setObjectName(QString::fromUtf8("lblVersion5D2"));
        lblVersion5D2->setGeometry(QRect(530, 200, 91, 40));
        lblVersion5D2->setAlignment(Qt::AlignCenter);

        retranslateUi(TableControl);

        QMetaObject::connectSlotsByName(TableControl);
    } // setupUi

    void retranslateUi(QDialog *TableControl)
    {
        TableControl->setWindowTitle(QApplication::translate("TableControl", "Dialog", 0, QApplication::UnicodeUTF8));
        lblVersion11A2->setText(QString());
        lblVersion6D1->setText(QString());
        lblVersion8A1->setText(QString());
        lblVersion4C2->setText(QString());
        lblVersion1D1->setText(QString());
        lblVersion9A2->setText(QString());
        lblVersion4B2->setText(QString());
        lblVersion6C2->setText(QString());
        lblVersion5C2->setText(QString());
        lblVersion11B1->setText(QString());
        lblVersion1B2->setText(QString());
        lblVersion11B2->setText(QString());
        lblVersion10D2->setText(QString());
        lblVersion2A1->setText(QString());
        lblVersion10B1->setText(QString());
        lblTitle2->setText(QApplication::translate("TableControl", "\350\275\257\344\273\266\347\211\210\346\234\254", 0, QApplication::UnicodeUTF8));
        lblVersion4A1->setText(QString());
        lblVersion5B2->setText(QString());
        lblVersion10C1->setText(QString());
        lblVersion3A2->setText(QString());
        lblVersion6A1->setText(QString());
        lblVersion8B2->setText(QString());
        lblVersion10A2->setText(QString());
        lblVersion8D2->setText(QString());
        lblVersion1D2->setText(QString());
        lblVersion10D1->setText(QString());
        lblVersion3D2->setText(QString());
        lblVersion11D2->setText(QString());
        lblVersion7B1->setText(QString());
        lblVersion9B1->setText(QString());
        lblVersion4D1->setText(QString());
        lblVersion6A2->setText(QString());
        lblVersion6B1->setText(QString());
        lblVersion6B2->setText(QString());
        lblVersion11C1->setText(QString());
        lblVersion9D2->setText(QString());
        lblVersion4D2->setText(QString());
        lblVersion8B1->setText(QString());
        lblVersion7A1->setText(QString());
        lblVersion2B2->setText(QString());
        lblVersion2C1->setText(QString());
        lblDeviceName7->setText(QString());
        lblVersion9B2->setText(QString());
        lblTitle1->setText(QApplication::translate("TableControl", "\350\256\276\345\244\207\345\220\215\347\247\260", 0, QApplication::UnicodeUTF8));
        lblVersion4A2->setText(QString());
        lblVersion4B1->setText(QString());
        lblVersion10A1->setText(QString());
        lblVersion1C1->setText(QString());
        lblVersion3D1->setText(QString());
        lblVersion5A2->setText(QString());
        lblVersion9A1->setText(QString());
        lblVersion7C1->setText(QString());
        lblVersion4C1->setText(QString());
        lblVersion5D1->setText(QString());
        lblVersion8C1->setText(QString());
        lblVersion11A1->setText(QString());
        lblDeviceName9->setText(QString());
        lblVersion7D2->setText(QString());
        lblVersion5A1->setText(QString());
        lblVersion10C2->setText(QString());
        lblDeviceName5->setText(QString());
        lblDeviceName2->setText(QString());
        lblVersion9C1->setText(QString());
        lblVersion7D1->setText(QString());
        lblVersion2B1->setText(QString());
        lblVersion9C2->setText(QString());
        lblVersion3C2->setText(QString());
        lblDeviceName10->setText(QString());
        lblVersion3B1->setText(QString());
        lblVersion7C2->setText(QString());
        lblDeviceName8->setText(QString());
        lblVersion8A2->setText(QString());
        lblVersion5C1->setText(QString());
        lblVersion11D1->setText(QString());
        lblVersion6C1->setText(QString());
        lblVersion2D2->setText(QString());
        lblVersion8D1->setText(QString());
        lblVersion7A2->setText(QString());
        lblVersion1C2->setText(QString());
        lblVersion1A2->setText(QString());
        lblDeviceName6->setText(QString());
        lblVersion1B1->setText(QString());
        lblVersion7B2->setText(QString());
        lblVersion3B2->setText(QString());
        lblDeviceName1->setText(QString());
        lblVersion3A1->setText(QString());
        lblDeviceName3->setText(QString());
        lblVersion2A2->setText(QString());
        lblDeviceName4->setText(QString());
        lblVersion2C2->setText(QString());
        lblVersion6D2->setText(QString());
        lblVersion9D1->setText(QString());
        lblVersion8C2->setText(QString());
        lblVersion3C1->setText(QString());
        lblVersion1A1->setText(QString());
        lblVersion10B2->setText(QString());
        lblVersion5B1->setText(QString());
        lblVersion11C2->setText(QString());
        lblDeviceName11->setText(QString());
        lblVersion2D1->setText(QString());
        lblVersion5D2->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class TableControl: public Ui_TableControl {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_TABLECONTROL_H
