/********************************************************************************
** Form generated from reading UI file 'vehicleparameter.ui'
**
** Created: Tue Jun 20 23:39:16 2017
**      by: Qt User Interface Compiler version 4.6.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_VEHICLEPARAMETER_H
#define UI_VEHICLEPARAMETER_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_VehicleParameter
{
public:
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *lblSivVoltage6;
    QLabel *lblSivVoltage3;
    QLabel *lblSivVoltage4;
    QLabel *lblSivVoltage1;
    QLabel *lblSivVoltage8;
    QLabel *lblSivVoltage2;
    QLabel *lblSivVoltage7;
    QLabel *lblSivVoltage5;
    QLabel *lblMiddleVoltage6;
    QLabel *lblMiddleVoltage4;
    QLabel *lblMiddleVoltage1;
    QLabel *lblMiddleVoltage2;
    QLabel *lblMiddleVoltage7;
    QLabel *lblMiddleVoltage3;
    QLabel *lblMiddleVoltage5;
    QLabel *lblMiddleVoltage8;
    QLabel *lblMiddleCurrent3;
    QLabel *lblMiddleCurrent1;
    QLabel *lblMiddleCurrent2;
    QLabel *lblMiddleCurrent8;
    QLabel *lblMiddleCurrent6;
    QLabel *lblMiddleCurrent4;
    QLabel *lblMiddleCurrent5;
    QLabel *lblMiddleCurrent7;
    QLabel *lblBrakePower1;
    QLabel *lblBrakePower7;
    QLabel *lblBrakePower2;
    QLabel *lblBrakePower3;
    QLabel *lblBrakePower6;
    QLabel *lblBrakePower5;
    QLabel *lblBrakePower8;
    QLabel *lblBrakePower4;
    QLabel *lblBrakeTotalPower1;
    QLabel *lblBrakeTotalPower3;
    QLabel *lblTotalPower;
    QLabel *lblTotalLoad;
    QLabel *lblLoadB1;
    QLabel *lblLoadD1;
    QLabel *lblLoadC2;
    QLabel *lblLoadC1;
    QLabel *lblLoadA1;
    QLabel *lblLoadD2;
    QLabel *lblLoadA2;
    QLabel *lblLoadB2;
    QLabel *lblTotalPressureA1;
    QLabel *lblTotalPressureB1;
    QLabel *lblTotalPressureC1;
    QLabel *lblTotalPressureD1;
    QLabel *lblTotalPressureD2;
    QLabel *lblTotalPressureC2;
    QLabel *lblTotalPressureB2;
    QLabel *lblTotalPressureA2;
    QLabel *lblSpringPressure2A1;
    QLabel *lblSpringPressure2D2;
    QLabel *lblSpringPressure2A2;
    QLabel *lblSpringPressure1A1;
    QLabel *lblSpringPressure1B2;
    QLabel *lblSpringPressure2B1;
    QLabel *lblSpringPressure2C1;
    QLabel *lblSpringPressure1C1;
    QLabel *lblSpringPressure2B2;
    QLabel *lblSpringPressure1D2;
    QLabel *lblSpringPressure2D1;
    QLabel *lblSpringPressure1C2;
    QLabel *lblSpringPressure1A2;
    QLabel *lblSpringPressure1B1;
    QLabel *lblSpringPressure1D1;
    QLabel *lblSpringPressure2C2;
    QLabel *lblBrakeCylinderPressure1A1;
    QLabel *lblBrakeCylinderPressure2D2;
    QLabel *lblBrakeCylinderPressure1C1;
    QLabel *lblBrakeCylinderPressure1B1;
    QLabel *lblBrakeCylinderPressure2C2;
    QLabel *lblBrakeCylinderPressure2A2;
    QLabel *lblBrakeCylinderPressure2B2;
    QLabel *lblBrakeCylinderPressure1D1;
    QLabel *lblBatteryTemperatureA1;
    QLabel *lblBatteryTemperatureA2;
    QLabel *lblBatteryCurrentA2;
    QLabel *lblBarreryCurrentA1;
    QLabel *label_139;
    QLabel *lblPowerPlugB1;
    QLabel *lblPowerPlugB2;
    QLabel *lblBrakeCylinderPressure1B2;
    QLabel *lblBrakeCylinderPressure1D2;
    QLabel *lblBrakeCylinderPressure1A2;
    QLabel *lblBrakeCylinderPressure2A1;
    QLabel *lblBrakeCylinderPressure2D1;
    QLabel *lblBrakeCylinderPressure2B1;
    QLabel *lblBrakeCylinderPressure1C2;
    QLabel *lblBrakeCylinderPressure2C1;

    void setupUi(QWidget *VehicleParameter)
    {
        if (VehicleParameter->objectName().isEmpty())
            VehicleParameter->setObjectName(QString::fromUtf8("VehicleParameter"));
        VehicleParameter->resize(1024, 600);
        VehicleParameter->setStyleSheet(QString::fromUtf8("QLabel\n"
"{\n"
"	color: white;\n"
"	border: 2px groove, gray;\n"
"    border-color: gray;\n"
"	font: 18px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"	background-color: black;\n"
"}"));
        label_20 = new QLabel(VehicleParameter);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(38, 92, 171, 40));
        label_20->setAlignment(Qt::AlignCenter);
        label_21 = new QLabel(VehicleParameter);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(207, 92, 91, 40));
        label_21->setAlignment(Qt::AlignCenter);
        label_22 = new QLabel(VehicleParameter);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(296, 92, 91, 40));
        label_22->setAlignment(Qt::AlignCenter);
        label_23 = new QLabel(VehicleParameter);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(385, 92, 91, 40));
        label_23->setAlignment(Qt::AlignCenter);
        label_29 = new QLabel(VehicleParameter);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(38, 130, 171, 40));
        label_29->setAlignment(Qt::AlignCenter);
        label_30 = new QLabel(VehicleParameter);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(38, 168, 171, 40));
        label_30->setAlignment(Qt::AlignCenter);
        label_31 = new QLabel(VehicleParameter);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(38, 206, 171, 40));
        label_31->setAlignment(Qt::AlignCenter);
        label_32 = new QLabel(VehicleParameter);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(38, 244, 171, 40));
        label_32->setAlignment(Qt::AlignCenter);
        label_33 = new QLabel(VehicleParameter);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(38, 320, 171, 40));
        label_33->setAlignment(Qt::AlignCenter);
        label_34 = new QLabel(VehicleParameter);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(38, 358, 171, 40));
        label_34->setAlignment(Qt::AlignCenter);
        label_35 = new QLabel(VehicleParameter);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(38, 548, 171, 40));
        label_35->setAlignment(Qt::AlignCenter);
        label_36 = new QLabel(VehicleParameter);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(38, 396, 171, 40));
        label_36->setAlignment(Qt::AlignCenter);
        label_37 = new QLabel(VehicleParameter);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(38, 434, 171, 40));
        label_37->setAlignment(Qt::AlignCenter);
        label_38 = new QLabel(VehicleParameter);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(38, 510, 171, 40));
        label_38->setAlignment(Qt::AlignCenter);
        label_39 = new QLabel(VehicleParameter);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(38, 282, 171, 40));
        label_39->setAlignment(Qt::AlignCenter);
        label_24 = new QLabel(VehicleParameter);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(474, 92, 91, 40));
        label_24->setAlignment(Qt::AlignCenter);
        label_25 = new QLabel(VehicleParameter);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(563, 92, 91, 40));
        label_25->setAlignment(Qt::AlignCenter);
        label_26 = new QLabel(VehicleParameter);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(652, 92, 91, 40));
        label_26->setAlignment(Qt::AlignCenter);
        label_27 = new QLabel(VehicleParameter);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(741, 92, 91, 40));
        label_27->setAlignment(Qt::AlignCenter);
        label_28 = new QLabel(VehicleParameter);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(830, 92, 91, 40));
        label_28->setAlignment(Qt::AlignCenter);
        lblSivVoltage6 = new QLabel(VehicleParameter);
        lblSivVoltage6->setObjectName(QString::fromUtf8("lblSivVoltage6"));
        lblSivVoltage6->setGeometry(QRect(652, 130, 91, 40));
        lblSivVoltage6->setAlignment(Qt::AlignCenter);
        lblSivVoltage3 = new QLabel(VehicleParameter);
        lblSivVoltage3->setObjectName(QString::fromUtf8("lblSivVoltage3"));
        lblSivVoltage3->setGeometry(QRect(385, 130, 91, 40));
        lblSivVoltage3->setAlignment(Qt::AlignCenter);
        lblSivVoltage4 = new QLabel(VehicleParameter);
        lblSivVoltage4->setObjectName(QString::fromUtf8("lblSivVoltage4"));
        lblSivVoltage4->setGeometry(QRect(474, 130, 91, 40));
        lblSivVoltage4->setAlignment(Qt::AlignCenter);
        lblSivVoltage1 = new QLabel(VehicleParameter);
        lblSivVoltage1->setObjectName(QString::fromUtf8("lblSivVoltage1"));
        lblSivVoltage1->setGeometry(QRect(207, 130, 91, 40));
        lblSivVoltage1->setAlignment(Qt::AlignCenter);
        lblSivVoltage8 = new QLabel(VehicleParameter);
        lblSivVoltage8->setObjectName(QString::fromUtf8("lblSivVoltage8"));
        lblSivVoltage8->setGeometry(QRect(830, 130, 91, 40));
        lblSivVoltage8->setAlignment(Qt::AlignCenter);
        lblSivVoltage2 = new QLabel(VehicleParameter);
        lblSivVoltage2->setObjectName(QString::fromUtf8("lblSivVoltage2"));
        lblSivVoltage2->setGeometry(QRect(296, 130, 91, 40));
        lblSivVoltage2->setAlignment(Qt::AlignCenter);
        lblSivVoltage7 = new QLabel(VehicleParameter);
        lblSivVoltage7->setObjectName(QString::fromUtf8("lblSivVoltage7"));
        lblSivVoltage7->setGeometry(QRect(741, 130, 91, 40));
        lblSivVoltage7->setAlignment(Qt::AlignCenter);
        lblSivVoltage5 = new QLabel(VehicleParameter);
        lblSivVoltage5->setObjectName(QString::fromUtf8("lblSivVoltage5"));
        lblSivVoltage5->setGeometry(QRect(563, 130, 91, 40));
        lblSivVoltage5->setAlignment(Qt::AlignCenter);
        lblMiddleVoltage6 = new QLabel(VehicleParameter);
        lblMiddleVoltage6->setObjectName(QString::fromUtf8("lblMiddleVoltage6"));
        lblMiddleVoltage6->setGeometry(QRect(652, 168, 91, 40));
        lblMiddleVoltage6->setAlignment(Qt::AlignCenter);
        lblMiddleVoltage4 = new QLabel(VehicleParameter);
        lblMiddleVoltage4->setObjectName(QString::fromUtf8("lblMiddleVoltage4"));
        lblMiddleVoltage4->setGeometry(QRect(474, 168, 91, 40));
        lblMiddleVoltage4->setAlignment(Qt::AlignCenter);
        lblMiddleVoltage1 = new QLabel(VehicleParameter);
        lblMiddleVoltage1->setObjectName(QString::fromUtf8("lblMiddleVoltage1"));
        lblMiddleVoltage1->setGeometry(QRect(207, 168, 91, 40));
        lblMiddleVoltage1->setAlignment(Qt::AlignCenter);
        lblMiddleVoltage2 = new QLabel(VehicleParameter);
        lblMiddleVoltage2->setObjectName(QString::fromUtf8("lblMiddleVoltage2"));
        lblMiddleVoltage2->setGeometry(QRect(296, 168, 91, 40));
        lblMiddleVoltage2->setAlignment(Qt::AlignCenter);
        lblMiddleVoltage7 = new QLabel(VehicleParameter);
        lblMiddleVoltage7->setObjectName(QString::fromUtf8("lblMiddleVoltage7"));
        lblMiddleVoltage7->setGeometry(QRect(741, 168, 91, 40));
        lblMiddleVoltage7->setAlignment(Qt::AlignCenter);
        lblMiddleVoltage3 = new QLabel(VehicleParameter);
        lblMiddleVoltage3->setObjectName(QString::fromUtf8("lblMiddleVoltage3"));
        lblMiddleVoltage3->setGeometry(QRect(385, 168, 91, 40));
        lblMiddleVoltage3->setAlignment(Qt::AlignCenter);
        lblMiddleVoltage5 = new QLabel(VehicleParameter);
        lblMiddleVoltage5->setObjectName(QString::fromUtf8("lblMiddleVoltage5"));
        lblMiddleVoltage5->setGeometry(QRect(563, 168, 91, 40));
        lblMiddleVoltage5->setAlignment(Qt::AlignCenter);
        lblMiddleVoltage8 = new QLabel(VehicleParameter);
        lblMiddleVoltage8->setObjectName(QString::fromUtf8("lblMiddleVoltage8"));
        lblMiddleVoltage8->setGeometry(QRect(830, 168, 91, 40));
        lblMiddleVoltage8->setAlignment(Qt::AlignCenter);
        lblMiddleCurrent3 = new QLabel(VehicleParameter);
        lblMiddleCurrent3->setObjectName(QString::fromUtf8("lblMiddleCurrent3"));
        lblMiddleCurrent3->setGeometry(QRect(385, 206, 91, 40));
        lblMiddleCurrent3->setAlignment(Qt::AlignCenter);
        lblMiddleCurrent1 = new QLabel(VehicleParameter);
        lblMiddleCurrent1->setObjectName(QString::fromUtf8("lblMiddleCurrent1"));
        lblMiddleCurrent1->setGeometry(QRect(207, 206, 91, 40));
        lblMiddleCurrent1->setAlignment(Qt::AlignCenter);
        lblMiddleCurrent2 = new QLabel(VehicleParameter);
        lblMiddleCurrent2->setObjectName(QString::fromUtf8("lblMiddleCurrent2"));
        lblMiddleCurrent2->setGeometry(QRect(296, 206, 91, 40));
        lblMiddleCurrent2->setAlignment(Qt::AlignCenter);
        lblMiddleCurrent8 = new QLabel(VehicleParameter);
        lblMiddleCurrent8->setObjectName(QString::fromUtf8("lblMiddleCurrent8"));
        lblMiddleCurrent8->setGeometry(QRect(830, 206, 91, 40));
        lblMiddleCurrent8->setAlignment(Qt::AlignCenter);
        lblMiddleCurrent6 = new QLabel(VehicleParameter);
        lblMiddleCurrent6->setObjectName(QString::fromUtf8("lblMiddleCurrent6"));
        lblMiddleCurrent6->setGeometry(QRect(652, 206, 91, 40));
        lblMiddleCurrent6->setAlignment(Qt::AlignCenter);
        lblMiddleCurrent4 = new QLabel(VehicleParameter);
        lblMiddleCurrent4->setObjectName(QString::fromUtf8("lblMiddleCurrent4"));
        lblMiddleCurrent4->setGeometry(QRect(474, 206, 91, 40));
        lblMiddleCurrent4->setAlignment(Qt::AlignCenter);
        lblMiddleCurrent5 = new QLabel(VehicleParameter);
        lblMiddleCurrent5->setObjectName(QString::fromUtf8("lblMiddleCurrent5"));
        lblMiddleCurrent5->setGeometry(QRect(563, 206, 91, 40));
        lblMiddleCurrent5->setAlignment(Qt::AlignCenter);
        lblMiddleCurrent7 = new QLabel(VehicleParameter);
        lblMiddleCurrent7->setObjectName(QString::fromUtf8("lblMiddleCurrent7"));
        lblMiddleCurrent7->setGeometry(QRect(741, 206, 91, 40));
        lblMiddleCurrent7->setAlignment(Qt::AlignCenter);
        lblBrakePower1 = new QLabel(VehicleParameter);
        lblBrakePower1->setObjectName(QString::fromUtf8("lblBrakePower1"));
        lblBrakePower1->setGeometry(QRect(207, 244, 91, 40));
        lblBrakePower1->setAlignment(Qt::AlignCenter);
        lblBrakePower7 = new QLabel(VehicleParameter);
        lblBrakePower7->setObjectName(QString::fromUtf8("lblBrakePower7"));
        lblBrakePower7->setGeometry(QRect(741, 244, 91, 40));
        lblBrakePower7->setAlignment(Qt::AlignCenter);
        lblBrakePower2 = new QLabel(VehicleParameter);
        lblBrakePower2->setObjectName(QString::fromUtf8("lblBrakePower2"));
        lblBrakePower2->setGeometry(QRect(296, 244, 91, 40));
        lblBrakePower2->setAlignment(Qt::AlignCenter);
        lblBrakePower3 = new QLabel(VehicleParameter);
        lblBrakePower3->setObjectName(QString::fromUtf8("lblBrakePower3"));
        lblBrakePower3->setGeometry(QRect(385, 244, 91, 40));
        lblBrakePower3->setAlignment(Qt::AlignCenter);
        lblBrakePower6 = new QLabel(VehicleParameter);
        lblBrakePower6->setObjectName(QString::fromUtf8("lblBrakePower6"));
        lblBrakePower6->setGeometry(QRect(652, 244, 91, 40));
        lblBrakePower6->setAlignment(Qt::AlignCenter);
        lblBrakePower5 = new QLabel(VehicleParameter);
        lblBrakePower5->setObjectName(QString::fromUtf8("lblBrakePower5"));
        lblBrakePower5->setGeometry(QRect(563, 244, 91, 40));
        lblBrakePower5->setAlignment(Qt::AlignCenter);
        lblBrakePower8 = new QLabel(VehicleParameter);
        lblBrakePower8->setObjectName(QString::fromUtf8("lblBrakePower8"));
        lblBrakePower8->setGeometry(QRect(830, 244, 91, 40));
        lblBrakePower8->setAlignment(Qt::AlignCenter);
        lblBrakePower4 = new QLabel(VehicleParameter);
        lblBrakePower4->setObjectName(QString::fromUtf8("lblBrakePower4"));
        lblBrakePower4->setGeometry(QRect(474, 244, 91, 40));
        lblBrakePower4->setAlignment(Qt::AlignCenter);
        lblBrakeTotalPower1 = new QLabel(VehicleParameter);
        lblBrakeTotalPower1->setObjectName(QString::fromUtf8("lblBrakeTotalPower1"));
        lblBrakeTotalPower1->setGeometry(QRect(207, 282, 91, 40));
        lblBrakeTotalPower1->setAlignment(Qt::AlignCenter);
        lblBrakeTotalPower3 = new QLabel(VehicleParameter);
        lblBrakeTotalPower3->setObjectName(QString::fromUtf8("lblBrakeTotalPower3"));
        lblBrakeTotalPower3->setGeometry(QRect(830, 282, 91, 40));
        lblBrakeTotalPower3->setAlignment(Qt::AlignCenter);
        lblTotalPower = new QLabel(VehicleParameter);
        lblTotalPower->setObjectName(QString::fromUtf8("lblTotalPower"));
        lblTotalPower->setGeometry(QRect(296, 282, 536, 40));
        lblTotalPower->setAlignment(Qt::AlignCenter);
        lblTotalLoad = new QLabel(VehicleParameter);
        lblTotalLoad->setObjectName(QString::fromUtf8("lblTotalLoad"));
        lblTotalLoad->setGeometry(QRect(207, 548, 714, 40));
        lblTotalLoad->setAlignment(Qt::AlignCenter);
        lblLoadB1 = new QLabel(VehicleParameter);
        lblLoadB1->setObjectName(QString::fromUtf8("lblLoadB1"));
        lblLoadB1->setGeometry(QRect(296, 510, 91, 40));
        lblLoadB1->setAlignment(Qt::AlignCenter);
        lblLoadD1 = new QLabel(VehicleParameter);
        lblLoadD1->setObjectName(QString::fromUtf8("lblLoadD1"));
        lblLoadD1->setGeometry(QRect(474, 510, 91, 40));
        lblLoadD1->setAlignment(Qt::AlignCenter);
        lblLoadC2 = new QLabel(VehicleParameter);
        lblLoadC2->setObjectName(QString::fromUtf8("lblLoadC2"));
        lblLoadC2->setGeometry(QRect(652, 510, 91, 40));
        lblLoadC2->setAlignment(Qt::AlignCenter);
        lblLoadC1 = new QLabel(VehicleParameter);
        lblLoadC1->setObjectName(QString::fromUtf8("lblLoadC1"));
        lblLoadC1->setGeometry(QRect(385, 510, 91, 40));
        lblLoadC1->setAlignment(Qt::AlignCenter);
        lblLoadA1 = new QLabel(VehicleParameter);
        lblLoadA1->setObjectName(QString::fromUtf8("lblLoadA1"));
        lblLoadA1->setGeometry(QRect(207, 510, 91, 40));
        lblLoadA1->setAlignment(Qt::AlignCenter);
        lblLoadD2 = new QLabel(VehicleParameter);
        lblLoadD2->setObjectName(QString::fromUtf8("lblLoadD2"));
        lblLoadD2->setGeometry(QRect(563, 510, 91, 40));
        lblLoadD2->setAlignment(Qt::AlignCenter);
        lblLoadA2 = new QLabel(VehicleParameter);
        lblLoadA2->setObjectName(QString::fromUtf8("lblLoadA2"));
        lblLoadA2->setGeometry(QRect(830, 510, 91, 40));
        lblLoadA2->setAlignment(Qt::AlignCenter);
        lblLoadB2 = new QLabel(VehicleParameter);
        lblLoadB2->setObjectName(QString::fromUtf8("lblLoadB2"));
        lblLoadB2->setGeometry(QRect(741, 510, 91, 40));
        lblLoadB2->setAlignment(Qt::AlignCenter);
        lblTotalPressureA1 = new QLabel(VehicleParameter);
        lblTotalPressureA1->setObjectName(QString::fromUtf8("lblTotalPressureA1"));
        lblTotalPressureA1->setGeometry(QRect(207, 320, 91, 40));
        lblTotalPressureA1->setAlignment(Qt::AlignCenter);
        lblTotalPressureB1 = new QLabel(VehicleParameter);
        lblTotalPressureB1->setObjectName(QString::fromUtf8("lblTotalPressureB1"));
        lblTotalPressureB1->setGeometry(QRect(296, 320, 91, 40));
        lblTotalPressureB1->setAlignment(Qt::AlignCenter);
        lblTotalPressureC1 = new QLabel(VehicleParameter);
        lblTotalPressureC1->setObjectName(QString::fromUtf8("lblTotalPressureC1"));
        lblTotalPressureC1->setGeometry(QRect(385, 320, 91, 40));
        lblTotalPressureC1->setAlignment(Qt::AlignCenter);
        lblTotalPressureD1 = new QLabel(VehicleParameter);
        lblTotalPressureD1->setObjectName(QString::fromUtf8("lblTotalPressureD1"));
        lblTotalPressureD1->setGeometry(QRect(474, 320, 91, 40));
        lblTotalPressureD1->setAlignment(Qt::AlignCenter);
        lblTotalPressureD2 = new QLabel(VehicleParameter);
        lblTotalPressureD2->setObjectName(QString::fromUtf8("lblTotalPressureD2"));
        lblTotalPressureD2->setGeometry(QRect(563, 320, 91, 40));
        lblTotalPressureD2->setAlignment(Qt::AlignCenter);
        lblTotalPressureC2 = new QLabel(VehicleParameter);
        lblTotalPressureC2->setObjectName(QString::fromUtf8("lblTotalPressureC2"));
        lblTotalPressureC2->setGeometry(QRect(652, 320, 91, 40));
        lblTotalPressureC2->setAlignment(Qt::AlignCenter);
        lblTotalPressureB2 = new QLabel(VehicleParameter);
        lblTotalPressureB2->setObjectName(QString::fromUtf8("lblTotalPressureB2"));
        lblTotalPressureB2->setGeometry(QRect(741, 320, 91, 40));
        lblTotalPressureB2->setAlignment(Qt::AlignCenter);
        lblTotalPressureA2 = new QLabel(VehicleParameter);
        lblTotalPressureA2->setObjectName(QString::fromUtf8("lblTotalPressureA2"));
        lblTotalPressureA2->setGeometry(QRect(830, 320, 91, 40));
        lblTotalPressureA2->setAlignment(Qt::AlignCenter);
        lblSpringPressure2A1 = new QLabel(VehicleParameter);
        lblSpringPressure2A1->setObjectName(QString::fromUtf8("lblSpringPressure2A1"));
        lblSpringPressure2A1->setGeometry(QRect(251, 358, 47, 40));
        lblSpringPressure2A1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure2A1->setAlignment(Qt::AlignCenter);
        lblSpringPressure2D2 = new QLabel(VehicleParameter);
        lblSpringPressure2D2->setObjectName(QString::fromUtf8("lblSpringPressure2D2"));
        lblSpringPressure2D2->setGeometry(QRect(563, 358, 46, 40));
        lblSpringPressure2D2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure2D2->setAlignment(Qt::AlignCenter);
        lblSpringPressure2A2 = new QLabel(VehicleParameter);
        lblSpringPressure2A2->setObjectName(QString::fromUtf8("lblSpringPressure2A2"));
        lblSpringPressure2A2->setGeometry(QRect(830, 358, 47, 40));
        lblSpringPressure2A2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure2A2->setAlignment(Qt::AlignCenter);
        lblSpringPressure1A1 = new QLabel(VehicleParameter);
        lblSpringPressure1A1->setObjectName(QString::fromUtf8("lblSpringPressure1A1"));
        lblSpringPressure1A1->setGeometry(QRect(207, 358, 46, 40));
        lblSpringPressure1A1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure1A1->setAlignment(Qt::AlignCenter);
        lblSpringPressure1B2 = new QLabel(VehicleParameter);
        lblSpringPressure1B2->setObjectName(QString::fromUtf8("lblSpringPressure1B2"));
        lblSpringPressure1B2->setGeometry(QRect(786, 358, 47, 40));
        lblSpringPressure1B2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure1B2->setAlignment(Qt::AlignCenter);
        lblSpringPressure2B1 = new QLabel(VehicleParameter);
        lblSpringPressure2B1->setObjectName(QString::fromUtf8("lblSpringPressure2B1"));
        lblSpringPressure2B1->setGeometry(QRect(340, 358, 47, 40));
        lblSpringPressure2B1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure2B1->setAlignment(Qt::AlignCenter);
        lblSpringPressure2C1 = new QLabel(VehicleParameter);
        lblSpringPressure2C1->setObjectName(QString::fromUtf8("lblSpringPressure2C1"));
        lblSpringPressure2C1->setGeometry(QRect(429, 358, 47, 40));
        lblSpringPressure2C1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure2C1->setAlignment(Qt::AlignCenter);
        lblSpringPressure1C1 = new QLabel(VehicleParameter);
        lblSpringPressure1C1->setObjectName(QString::fromUtf8("lblSpringPressure1C1"));
        lblSpringPressure1C1->setGeometry(QRect(385, 358, 46, 40));
        lblSpringPressure1C1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure1C1->setAlignment(Qt::AlignCenter);
        lblSpringPressure2B2 = new QLabel(VehicleParameter);
        lblSpringPressure2B2->setObjectName(QString::fromUtf8("lblSpringPressure2B2"));
        lblSpringPressure2B2->setGeometry(QRect(741, 358, 47, 40));
        lblSpringPressure2B2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure2B2->setAlignment(Qt::AlignCenter);
        lblSpringPressure1D2 = new QLabel(VehicleParameter);
        lblSpringPressure1D2->setObjectName(QString::fromUtf8("lblSpringPressure1D2"));
        lblSpringPressure1D2->setGeometry(QRect(607, 358, 47, 40));
        lblSpringPressure1D2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure1D2->setAlignment(Qt::AlignCenter);
        lblSpringPressure2D1 = new QLabel(VehicleParameter);
        lblSpringPressure2D1->setObjectName(QString::fromUtf8("lblSpringPressure2D1"));
        lblSpringPressure2D1->setGeometry(QRect(518, 358, 47, 40));
        lblSpringPressure2D1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure2D1->setAlignment(Qt::AlignCenter);
        lblSpringPressure1C2 = new QLabel(VehicleParameter);
        lblSpringPressure1C2->setObjectName(QString::fromUtf8("lblSpringPressure1C2"));
        lblSpringPressure1C2->setGeometry(QRect(696, 358, 47, 40));
        lblSpringPressure1C2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure1C2->setAlignment(Qt::AlignCenter);
        lblSpringPressure1A2 = new QLabel(VehicleParameter);
        lblSpringPressure1A2->setObjectName(QString::fromUtf8("lblSpringPressure1A2"));
        lblSpringPressure1A2->setGeometry(QRect(874, 358, 47, 40));
        lblSpringPressure1A2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure1A2->setAlignment(Qt::AlignCenter);
        lblSpringPressure1B1 = new QLabel(VehicleParameter);
        lblSpringPressure1B1->setObjectName(QString::fromUtf8("lblSpringPressure1B1"));
        lblSpringPressure1B1->setGeometry(QRect(296, 358, 46, 40));
        lblSpringPressure1B1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure1B1->setAlignment(Qt::AlignCenter);
        lblSpringPressure1D1 = new QLabel(VehicleParameter);
        lblSpringPressure1D1->setObjectName(QString::fromUtf8("lblSpringPressure1D1"));
        lblSpringPressure1D1->setGeometry(QRect(474, 358, 46, 40));
        lblSpringPressure1D1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure1D1->setAlignment(Qt::AlignCenter);
        lblSpringPressure2C2 = new QLabel(VehicleParameter);
        lblSpringPressure2C2->setObjectName(QString::fromUtf8("lblSpringPressure2C2"));
        lblSpringPressure2C2->setGeometry(QRect(652, 358, 46, 40));
        lblSpringPressure2C2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblSpringPressure2C2->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure1A1 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure1A1->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure1A1"));
        lblBrakeCylinderPressure1A1->setGeometry(QRect(207, 396, 46, 40));
        lblBrakeCylinderPressure1A1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure1A1->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure2D2 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure2D2->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure2D2"));
        lblBrakeCylinderPressure2D2->setGeometry(QRect(563, 396, 46, 40));
        lblBrakeCylinderPressure2D2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure2D2->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure1C1 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure1C1->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure1C1"));
        lblBrakeCylinderPressure1C1->setGeometry(QRect(385, 396, 46, 40));
        lblBrakeCylinderPressure1C1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure1C1->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure1B1 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure1B1->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure1B1"));
        lblBrakeCylinderPressure1B1->setGeometry(QRect(296, 396, 46, 40));
        lblBrakeCylinderPressure1B1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure1B1->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure2C2 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure2C2->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure2C2"));
        lblBrakeCylinderPressure2C2->setGeometry(QRect(652, 396, 46, 40));
        lblBrakeCylinderPressure2C2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure2C2->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure2A2 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure2A2->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure2A2"));
        lblBrakeCylinderPressure2A2->setGeometry(QRect(830, 396, 46, 40));
        lblBrakeCylinderPressure2A2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure2A2->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure2B2 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure2B2->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure2B2"));
        lblBrakeCylinderPressure2B2->setGeometry(QRect(741, 396, 47, 40));
        lblBrakeCylinderPressure2B2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure2B2->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure1D1 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure1D1->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure1D1"));
        lblBrakeCylinderPressure1D1->setGeometry(QRect(474, 396, 46, 40));
        lblBrakeCylinderPressure1D1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure1D1->setAlignment(Qt::AlignCenter);
        lblBatteryTemperatureA1 = new QLabel(VehicleParameter);
        lblBatteryTemperatureA1->setObjectName(QString::fromUtf8("lblBatteryTemperatureA1"));
        lblBatteryTemperatureA1->setGeometry(QRect(207, 434, 358, 40));
        lblBatteryTemperatureA1->setAlignment(Qt::AlignCenter);
        lblBatteryTemperatureA2 = new QLabel(VehicleParameter);
        lblBatteryTemperatureA2->setObjectName(QString::fromUtf8("lblBatteryTemperatureA2"));
        lblBatteryTemperatureA2->setGeometry(QRect(563, 434, 358, 40));
        lblBatteryTemperatureA2->setAlignment(Qt::AlignCenter);
        lblBatteryCurrentA2 = new QLabel(VehicleParameter);
        lblBatteryCurrentA2->setObjectName(QString::fromUtf8("lblBatteryCurrentA2"));
        lblBatteryCurrentA2->setGeometry(QRect(563, 472, 358, 40));
        lblBatteryCurrentA2->setAlignment(Qt::AlignCenter);
        lblBarreryCurrentA1 = new QLabel(VehicleParameter);
        lblBarreryCurrentA1->setObjectName(QString::fromUtf8("lblBarreryCurrentA1"));
        lblBarreryCurrentA1->setGeometry(QRect(207, 472, 358, 40));
        lblBarreryCurrentA1->setAlignment(Qt::AlignCenter);
        label_139 = new QLabel(VehicleParameter);
        label_139->setObjectName(QString::fromUtf8("label_139"));
        label_139->setGeometry(QRect(38, 472, 171, 40));
        label_139->setAlignment(Qt::AlignCenter);
        lblPowerPlugB1 = new QLabel(VehicleParameter);
        lblPowerPlugB1->setObjectName(QString::fromUtf8("lblPowerPlugB1"));
        lblPowerPlugB1->setGeometry(QRect(326, 95, 32, 32));
        lblPowerPlugB1->setStyleSheet(QString::fromUtf8("border: 0px;\n"
"border-image: url(:/images/garagePowerRun.png);"));
        lblPowerPlugB1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblPowerPlugB2 = new QLabel(VehicleParameter);
        lblPowerPlugB2->setObjectName(QString::fromUtf8("lblPowerPlugB2"));
        lblPowerPlugB2->setGeometry(QRect(770, 95, 32, 32));
        lblPowerPlugB2->setStyleSheet(QString::fromUtf8("border: 0px;\n"
"border-image: url(:/images/garagePowerStop.png);"));
        lblPowerPlugB2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblBrakeCylinderPressure1B2 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure1B2->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure1B2"));
        lblBrakeCylinderPressure1B2->setGeometry(QRect(786, 396, 47, 40));
        lblBrakeCylinderPressure1B2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure1B2->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure1D2 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure1D2->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure1D2"));
        lblBrakeCylinderPressure1D2->setGeometry(QRect(607, 396, 47, 40));
        lblBrakeCylinderPressure1D2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure1D2->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure1A2 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure1A2->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure1A2"));
        lblBrakeCylinderPressure1A2->setGeometry(QRect(874, 396, 47, 40));
        lblBrakeCylinderPressure1A2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure1A2->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure2A1 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure2A1->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure2A1"));
        lblBrakeCylinderPressure2A1->setGeometry(QRect(251, 396, 47, 40));
        lblBrakeCylinderPressure2A1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure2A1->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure2D1 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure2D1->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure2D1"));
        lblBrakeCylinderPressure2D1->setGeometry(QRect(518, 396, 47, 40));
        lblBrakeCylinderPressure2D1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure2D1->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure2B1 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure2B1->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure2B1"));
        lblBrakeCylinderPressure2B1->setGeometry(QRect(340, 396, 47, 40));
        lblBrakeCylinderPressure2B1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure2B1->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure1C2 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure1C2->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure1C2"));
        lblBrakeCylinderPressure1C2->setGeometry(QRect(696, 396, 47, 40));
        lblBrakeCylinderPressure1C2->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure1C2->setAlignment(Qt::AlignCenter);
        lblBrakeCylinderPressure2C1 = new QLabel(VehicleParameter);
        lblBrakeCylinderPressure2C1->setObjectName(QString::fromUtf8("lblBrakeCylinderPressure2C1"));
        lblBrakeCylinderPressure2C1->setGeometry(QRect(429, 396, 47, 40));
        lblBrakeCylinderPressure2C1->setStyleSheet(QString::fromUtf8("font: 15px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        lblBrakeCylinderPressure2C1->setAlignment(Qt::AlignCenter);

        retranslateUi(VehicleParameter);

        QMetaObject::connectSlotsByName(VehicleParameter);
    } // setupUi

    void retranslateUi(QWidget *VehicleParameter)
    {
        VehicleParameter->setWindowTitle(QApplication::translate("VehicleParameter", "Form", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("VehicleParameter", "\345\272\223\347\224\250\347\224\265\346\272\220\347\233\221\350\247\206", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        label_22->setText(QString());
        label_23->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("VehicleParameter", "SIV\347\272\277\347\224\265\345\216\213", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("VehicleParameter", "\344\270\255\351\227\264\347\224\265\345\216\213", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("VehicleParameter", "\344\270\255\351\227\264\347\224\265\346\265\201", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("VehicleParameter", "\347\211\265\345\274\225\345\210\266\345\212\250\345\212\233", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("VehicleParameter", "\346\200\273\351\243\216\345\216\213\345\212\233(Bar)", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("VehicleParameter", "\347\251\272\347\260\247\345\216\213\345\212\233(Bar)", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("VehicleParameter", "\345\210\227\350\275\246\346\200\273\350\275\275\351\207\215", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("VehicleParameter", "\345\210\266\345\212\250\347\274\270\345\216\213\345\212\233(Bar)", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("VehicleParameter", "\350\223\204\347\224\265\346\261\240\346\270\251\345\272\246", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("VehicleParameter", "\350\275\275\351\207\215", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("VehicleParameter", "\346\200\273\347\211\265\345\274\225\345\210\266\345\212\250\345\212\233", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        label_27->setText(QString());
        label_28->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblSivVoltage6->setText(QString());
        lblSivVoltage3->setText(QString());
        lblSivVoltage4->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblSivVoltage1->setText(QString());
        lblSivVoltage8->setText(QString());
        lblSivVoltage2->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblSivVoltage7->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblSivVoltage5->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblMiddleVoltage6->setText(QString());
        lblMiddleVoltage4->setText(QString());
        lblMiddleVoltage1->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblMiddleVoltage2->setText(QString());
        lblMiddleVoltage7->setText(QString());
        lblMiddleVoltage3->setText(QString());
        lblMiddleVoltage5->setText(QString());
        lblMiddleVoltage8->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblMiddleCurrent3->setText(QString());
        lblMiddleCurrent1->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblMiddleCurrent2->setText(QString());
        lblMiddleCurrent8->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblMiddleCurrent6->setText(QString());
        lblMiddleCurrent4->setText(QString());
        lblMiddleCurrent5->setText(QString());
        lblMiddleCurrent7->setText(QString());
        lblBrakePower1->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblBrakePower7->setText(QString());
        lblBrakePower2->setText(QString());
        lblBrakePower3->setText(QString());
        lblBrakePower6->setText(QString());
        lblBrakePower5->setText(QString());
        lblBrakePower8->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblBrakePower4->setText(QString());
        lblBrakeTotalPower1->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblBrakeTotalPower3->setText(QApplication::translate("VehicleParameter", "\357\274\215\357\274\215", 0, QApplication::UnicodeUTF8));
        lblTotalPower->setText(QString());
        lblTotalLoad->setText(QString());
        lblLoadB1->setText(QString());
        lblLoadD1->setText(QString());
        lblLoadC2->setText(QString());
        lblLoadC1->setText(QString());
        lblLoadA1->setText(QString());
        lblLoadD2->setText(QString());
        lblLoadA2->setText(QString());
        lblLoadB2->setText(QString());
        lblTotalPressureA1->setText(QString());
        lblTotalPressureB1->setText(QApplication::translate("VehicleParameter", "- -", 0, QApplication::UnicodeUTF8));
        lblTotalPressureC1->setText(QString());
        lblTotalPressureD1->setText(QString());
        lblTotalPressureD2->setText(QString());
        lblTotalPressureC2->setText(QString());
        lblTotalPressureB2->setText(QApplication::translate("VehicleParameter", "- -", 0, QApplication::UnicodeUTF8));
        lblTotalPressureA2->setText(QString());
        lblSpringPressure2A1->setText(QString());
        lblSpringPressure2D2->setText(QString());
        lblSpringPressure2A2->setText(QString());
        lblSpringPressure1A1->setText(QString());
        lblSpringPressure1B2->setText(QString());
        lblSpringPressure2B1->setText(QString());
        lblSpringPressure2C1->setText(QString());
        lblSpringPressure1C1->setText(QString());
        lblSpringPressure2B2->setText(QString());
        lblSpringPressure1D2->setText(QString());
        lblSpringPressure2D1->setText(QString());
        lblSpringPressure1C2->setText(QString());
        lblSpringPressure1A2->setText(QString());
        lblSpringPressure1B1->setText(QString());
        lblSpringPressure1D1->setText(QString());
        lblSpringPressure2C2->setText(QString());
        lblBrakeCylinderPressure1A1->setText(QString());
        lblBrakeCylinderPressure2D2->setText(QString());
        lblBrakeCylinderPressure1C1->setText(QString());
        lblBrakeCylinderPressure1B1->setText(QString());
        lblBrakeCylinderPressure2C2->setText(QString());
        lblBrakeCylinderPressure2A2->setText(QString());
        lblBrakeCylinderPressure2B2->setText(QString());
        lblBrakeCylinderPressure1D1->setText(QString());
        lblBatteryTemperatureA1->setText(QString());
        lblBatteryTemperatureA2->setText(QString());
        lblBatteryCurrentA2->setText(QString());
        lblBarreryCurrentA1->setText(QString());
        label_139->setText(QApplication::translate("VehicleParameter", "\350\223\204\347\224\265\346\261\240\345\205\205\346\224\276\347\224\265\347\224\265\346\265\201", 0, QApplication::UnicodeUTF8));
        lblPowerPlugB1->setText(QString());
        lblPowerPlugB2->setText(QString());
        lblBrakeCylinderPressure1B2->setText(QString());
        lblBrakeCylinderPressure1D2->setText(QString());
        lblBrakeCylinderPressure1A2->setText(QString());
        lblBrakeCylinderPressure2A1->setText(QString());
        lblBrakeCylinderPressure2D1->setText(QString());
        lblBrakeCylinderPressure2B1->setText(QString());
        lblBrakeCylinderPressure1C2->setText(QString());
        lblBrakeCylinderPressure2C1->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class VehicleParameter: public Ui_VehicleParameter {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VEHICLEPARAMETER_H
